#!/usr/bin/env python3
"""Anti-drift audit: every quoted heredoc in setup-rag-*.sh must match its
live generated file.

The setup-rag-*.sh scripts are the source of truth: they emit lib/*.py and the
wrapper scripts via heredocs. The generated files are untracked, so they can
silently drift from the heredocs that produce them. Run this after editing a
generated file to confirm the change was mirrored back into the setup script
(and vice versa).

Exit code 0 = all in sync, 1 = drift or missing file detected.

Usage:  ./audit-heredocs.py
"""
import re
import sys
import glob
import os

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
os.chdir(PROJECT_DIR)

# cat > "$PROJECT_DIR/<path>" << 'MARKER'   (quoted   = literal body)
# cat > "$PROJECT_DIR/<path>" << MARKER     (unquoted = vars expanded at gen time)
HEADER = re.compile(
    r'''^cat\s*>\s*"\$(?:\{)?PROJECT_DIR(?:\})?/(?P<path>[^"]+)"\s*<<\s*'''
    r'''(?P<q>['"]?)(?P<marker>[\w-]+)(?P=q)\s*$'''
)


def main():
    targets = {}   # path -> set of setup files that generate it
    results = []    # (status, setup, path, note)

    for setup in sorted(glob.glob("setup-rag-*.sh")):
        with open(setup, encoding="utf-8", errors="replace") as fh:
            lines = fh.readlines()
        i = 0
        while i < len(lines):
            m = HEADER.match(lines[i].rstrip("\n"))
            if not m:
                i += 1
                continue
            path, quoted, marker = m.group("path"), bool(m.group("q")), m.group("marker")
            body = []
            j = i + 1
            while j < len(lines) and lines[j].rstrip("\n") != marker:
                body.append(lines[j])
                j += 1
            targets.setdefault(path, set()).add(setup)

            if not quoted:
                results.append(("SKIP-EXPAND", setup, path,
                                "unquoted heredoc (vars expanded at gen time)"))
            elif not os.path.exists(os.path.join(PROJECT_DIR, path)):
                results.append(("MISSING", setup, path, "live file absent (setup not run?)"))
            else:
                with open(os.path.join(PROJECT_DIR, path), encoding="utf-8",
                          errors="replace") as lf:
                    live = lf.read()
                heredoc = "".join(body)
                if live == heredoc:
                    results.append(("OK", setup, path, ""))
                else:
                    results.append(("DRIFT", setup, path,
                                    f"heredoc={len(heredoc.splitlines())}L "
                                    f"live={len(live.splitlines())}L"))
            i = j + 1

    for status in ("DRIFT", "MISSING", "SKIP-EXPAND", "OK"):
        rows = [r for r in results if r[0] == status]
        if rows:
            print(f"\n=== {status} ({len(rows)}) ===")
            for _, setup, path, note in rows:
                print(f"  {setup:28} {path:40} {note}")

    dups = {p: s for p, s in targets.items() if len(s) > 1}
    if dups:
        print(f"\n=== FILE GENERATED BY >1 SETUP SCRIPT ({len(dups)}) ===")
        for p, s in dups.items():
            print(f"  {p:40} <- {sorted(s)}")

    n_drift = sum(1 for r in results if r[0] == "DRIFT")
    n_missing = sum(1 for r in results if r[0] == "MISSING")
    n_ok = sum(1 for r in results if r[0] == "OK")
    n_skip = sum(1 for r in results if r[0] == "SKIP-EXPAND")
    print(f"\nSUMMARY: {n_drift} drift, {n_missing} missing, {n_ok} ok, {n_skip} skipped")
    return 1 if (n_drift or n_missing) else 0


if __name__ == "__main__":
    sys.exit(main())
